In [ ]:
# default_exp neural_network

In [ ]:
#hide
from nbdev.showdoc import *

ModuleNotFoundError: No module named 'nbdev'

# Neural Network
> Summary: Classification, Neural Network, Gradient Descent, Backpropagation, Overfitting, Regularization

## What's a neural network?

Without delving into brain analogies, I simply describe neural network as an algorithm for approximating functions. In the context of machine learning, neural network is a function that maps input to desired output, given a set of inputs $x$ and output $y$.

Neural networks are a collection of a densely interconnected set of simple units, organazied into a *input layer*, one or more *hidden layers* and an *output layer*.

The diagram below shows an architecture of a 3-layer neural network.

![](images/nn_ex_2.jpeg)
*Fig1. A 3-layer neural network with three inputs, two hidden layers of 4 neurons each and one output layer. [[Image Source]](http://cs231n.github.io/neural-networks-1/)*

## Perceptron

Perceptron is a single neuron that calculates a linear combination of the input (i.e. performs a dot product with the input and its weights), adds a bias $b$, applies the non-linearity (or activation function), and outputs a value. If the activation function is sigmoid $\sigma$, the output is a number between 0 and 1.

$$\hat{y}=\sigma(b + \sum_{i=1}^n w_ix_i)$$

where $\sigma (t)=\frac{1}{1+e^{-t}}$

![](images/nn_perceptron.jpeg)
*Fig2. Representation of Perceptron*


## Common Activation Functions

1- **Sigmoid**. Sigmoid function takes a real-valued number and "squashes" it into range between 0 and 1. In particular, large negative numbers become 0 and large positive numbers become 1.

2- **Tanh**. Tanh function $tanh(x)=2\sigma(2x)-1$ squashes a real-valued number to the range [-1, 1]. Its output is zero-centered. Please note that the tanh neuron is simply a scaled sigmoid neuron.

3- **ReLU**. The Rectified Linear Unit has become very popular in the last few years. It computes the function $f(x)=max(0,x)$. In other words, the activation is simply thresholded at zero.

## Importance of Activation Functions

The purpose of activation functions is to introduce ***non-linearity*** into the network, which enables the network to separate the data that is not linearly separable. Linear functions always create linear decisions while non-linear functions allow to approximate arbitrarily complex functions.

![](images/nn_linear.png)
![](images/nn_nonlinear.png)
*Fig3. Left: Linear activation functions produce linear decisions. Right: Non-Linear activation functions produce non-linear decisions*. You can play with these examples in this [ConvNetsJS demo](http://cs.stanford.edu/people/karpathy/convnetjs/demo/classify2d.html)



## Perceptron Simplified

We usually simplify the perceptron representation as below.

![](images/nn_perceptron_2.jpeg)
*Fig5. Simplified perceptron*

## Training a Neural Network

We will see how we can train a neural network through an example. Let's assume that our neural network architecture looks like the image shown below.

![](images/nn_ex_1.jpeg)

We can see that the weights $\mathbf{W}$ and biases $\mathbf{b}$ are the only variables that affect the output $\hat{y}$. Therefore, training a neural network essentially means finding the right values for the weights and biases so that they can determine the best predictions. In other words, the process of fine-tuning the weights and biases from the input data is called training neural network.

Training a neural network involves two steps:

- Feed-forward computation
   
- backpropagation

### Feed-forward computation

Feed-forward step fundamentally means *repeated matrix multiplications combined with activation function*. Considering our example network, we convert the different variables into vectors and matrices. Therefore, the input  would be a [3x1] vector. The weights of the hidden layer `W1` would be a [4x3] matrix, and its biases `b1` would be a [4x1] vector. In this layer, each neuron has its weights in a row of `W1`, so the matrix vector multiplication `np.dot(W1,x)` evaluates the activations of all neurons in this layer. For the last layer (output layer), `W2` and `b2` would be of size [1x4] and [1x1], respectively. The full forward pass of this 3-layer neural network is then simply three matrix multiplications, merged with the application of the activation function:

![](images/nn_forward.jpeg)

Therefore, the forward-pass is:

![](images/nn_forward_full.jpeg)


We need to learn the Parameters `W1,W2,b1,b2` of the above network. Please note that the input `x` could be an entire batch of training data, where each example would be a column of `x`.

> Note: The forward pass of a fully-connected layer corresponds to one matrix multiplication followed by a bias offset and an activation function.

### Loss Function

performing a forward-pass of the network gives us the predictions. Therefore, we must evaluate the "goodness" of our predictions, which means we need to measure how far off our predictions are. **Loss function** enables us to do that. The loss function measures the cost caused by incorrect predictions.

if $\mathcal{L}(\hat{y}^{(i)},y^{(i)})$ is the loss of each example $i$ in the training set, for $i=1,2,\cdots,m$, then total loss $J(W)$ over the entire dataset is:

$$J(W)=\frac{1}{m}\sum_{i=1}^m \mathcal{L}(\hat{y}^{(i)},y^{(i)})$$

Please note that $W=[W^{(1)}, W^{(2)},\cdots, W^{(L)}]$, where $W^{(j)}$ is matrix of weights of layer $j$

### Cross Entropy Loss

Cross entropy loss is used in classification problems and outputs a probability between 0 and 0.

$$J(W)=\frac{1}{m}\sum_{i=1}^m \left[ y^{(i)}\log(\hat{y}^{(i)}) + (1-y^{(i)})\log(1-\hat{y}^{(i)})\right]$$

### Mean Squared Error Loss

Mean squared error loss is used in regression problems and outputs a real-valued number.

$$J(W)=\frac{1}{m}\sum_{i=1}^m \left( y^{(i)} - \hat{y}^{(i)} \right)^2$$


### Backpropagation


Our goal in training is to find the weights and biases that minimizes the loss function:

$$W^* = \underset{W}{\arg\min}\ J(W)$$

After we measured the loss, we need to find a way to **propagate** the error back, and update our weights and biases, in order to decrease the loss. But how much should we adjust the weights and biases.

In order to find the appropriate amount of change in the weights and biases, we need to take the derivative of the loss function with respect to the weights and biases. The process of computing gradients of expressions through recursive application of chain rule is called **backpropagation**. When we have the gradients, we can use the *gradient descent* algorithm to update the weights.

Gradient descent algorithm:
1. Initialize the weights randomly $\sim N(0,\sigma^2)$
2. Loop until convergence:
   1. Compute gradient, $\frac{\partial J(\mathbf{W})}{\partial \mathbf{W}}$
   2. Update weights, $W = W-\eta \frac{\partial J(W)}{\partial W}$
3. Return weights

For instance, if we are going to compute the gradient with respect to $w_1$, in our example network below, we have:
![](images/nn_backprop.jpeg)

We need to repeat this **for every weight in the network** using gradients from later layers.


The full backpropagation of our model is: ($\odot$ is the element-wise multiplication)

![](images/nn_backprop_full.jpeg)

In [ ]:
#hide
import numpy as np
import pandas as pd
import altair as alt

x = np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]))
y = np.array(([0],[1],[1],[0]))

n_hidden_units = 10

class NeuralNetwork:
    
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.y_hat = np. zeros(y.shape)
        
        self.W1 = np.random.randn(x.shape[1],n_hidden_units)
        self.W2 = np.random.randn(n_hidden_units,1)
        self.b1 = np.zeros((1,n_hidden_units))
        self.b2 = np.zeros((1,1))
        self.learning_rate = 0.01
        
          
    def sigmoid(self,x):
        return 1 / (1 + np.exp(-x))
    
    
    def deriv_sigmoid(self,x):
        return x * (1 - x)

    
    def feedforward(self):
        z1 = np.dot(self.x,self.W1) + self.b1
        self.a1 = self.sigmoid(z1)
        z2 = np.dot(self.a1,self.W2) + self.b2
        self.y_hat  = self.sigmoid(z2)


    def cross_entropy(self):
        loss = -np.mean(self.y * np.log(self.y_hat) + (1 - self.y) * np.log(1 - self.y_hat))
        return loss


    def backprop(self):
        delta_2 = self.y_hat - self.y
        dW2 = np.dot(self.a1.T,delta_2)
        db2 = delta_2
        z2_delta = np.dot(delta_2,self.W2.T)
        delta_1 = z2_delta * self.deriv_sigmoid(self.a1)
        dW1 = np.dot(self.x.T,delta_1)
        db1 = delta_1
    
        self.W2 = self.W2 - self.learning_rate * dW2
        self.b2 = self.b2 - self.learning_rate * db2
        self.W1 = self.W1 - self.learning_rate * dW1
        self.b1 = self.b1 - self.learning_rate * db1

#         self.W2 -= self.learning_rate * dW2
#         self.b2 -= self.learning_rate * db2
#         self.W1 -= self.learning_rate * dW1
#         self.b1 -= self.learning_rate * db1
        
    def train(self):
        self.feedforward()
        self.backprop()


    
nn = NeuralNetwork(x,y)

for i in range(1,1001):
    nn.train()
    if i % 1000 == 0:
        print("Iteration: {}".format(i))
        print("Actual Output: {}".format(nn.y.flatten()))
        print("Predicted Output: {}".format(nn.y_hat.flatten()))
        loss = nn.cross_entropy()
        print("loss: {}".format(loss))    

bb1 = nn.b2
bb1.shape

In [ ]:
#hide
import numpy as np 
      
# Each row is a training example, each column is a feature  [X1, X2, X3]
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)

# Define useful functions    

# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
#         print("layer1:",self.layer1.shape)
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
#         print("layer2:",self.layer1.shape)
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()
        

NN = NeuralNetwork(X,y)
for i in range(1,1001): # trains the NN 1,000 times
    if i % 1000 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
  
    NN.train(X, y)

for iteration # 1000

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.01382207]
 [0.96366289]
 [0.96485941]
 [0.04136934]]
Loss: 
0.0011144296435900503


